name: PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  deployments: write
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/run-precommit

  publish-preview:
    if: github.repository == 'pembsclimbingclub/pcc-website'
    runs-on: ubuntu-latest
    # Supplies CLOUDFLARE_API_TOKEN and CLOUDFLARE_ACCOUNT_ID
    environment: cloudflare-pr
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/publish-to-cloudflare-pages
        with:
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          branch-name: ${{ github.head_ref }}
          project-name: pcc-website
          github-token: ${{ secrets.GITHUB_TOKEN }}
